### ISSUE TITLE
Radius authentication fails on 1.6.0

### ISSUE THREAD

**Issue by jonare77** [phpipam-docker/phpipam-docker#39]
After upgrading container from latest 1.5.x to 1.6.0 radius authentication fails with following message in container:

```
10.40.0.4 - - [18/Dec/2023:13:37:21 +0100] "GET /login/ HTTP/1.1" 200 1724 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
[Mon Dec 18 13:37:23.595496 2023] [php:error] [pid 25] [client 10.40.0.4:42668] PHP Fatal error:  Uncaught TypeError: count(): Argument #1 ($value) must be of type Countable|array, null given in /phpipam/functions/classes/class.Radius.php:579\nStack trace:\n#0 /phpipam/functions/classes/class.Radius.php(397): Radius->SetAttribute()\n#1 /phpipam/functions/classes/class.Radius.php(697): Radius->SetUsername()\n#2 /phpipam/functions/classes/class.User.php(1185): Radius->AccessRequest()\n#3 /phpipam/functions/classes/class.User.php(837): User->auth_radius()\n#4 /phpipam/app/login/login_check.php(51): User->authenticate()\n#5 {main}\n  thrown in /phpipam/functions/classes/class.Radius.php on line 579, referer: https://ipam.ipam.xxxxx.xxxxx.no.no/login/
10.40.0.4 - - [18/Dec/2023:13:37:23 +0100] "POST /app/login/login_check.php HTTP/1.1" 500 20 "https://ipam.xxxxx.xxxxx.no/login/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
```

**Comment by jonare77** [comment]
.
